---

- name: Avvia Docker Registry container
  community.docker.docker_container:
    name: "{{ registry_name }}"
    image: "{{ registry_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ registry_port }}:{{ registry_port }}"

  