- name: Controlla che l'engine sia supportato
  fail:
    msg: "Engine '{{ container_engine }}' non supportato. Usa 'docker' o 'podman'."
  when: container_engine not in ['docker', 'podman']

- name: Importa i task per Docker
  import_tasks: docker-registry.yaml
  when: container_engine == 'docker'

- name: Importa i task per Podman
  import_tasks: podman-registry.yaml
  when: container_engine == 'podman'
#cambia il valore di "container_engine" nel file /vars/main.yaml